title: Vanessa Cassandra
description: > # this means to ignore newlines until "baseurl:"
  Application Engineer in an automation company. This site is to keep a diary of my learning journey.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vancass.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vanessa Cassandra # add your name
author-img: profile.jpg # add your photo
about-author: An engineer who likes to build things. # add description
social-twitter: vancassa # add your Twitter handle
social-facebook: vanessa.cassandra.1 # add your Facebook handle
social-github: vancass # add your Github handle
social-linkedin: vanessa-cassandra-0b567b25 # add your Linkedin handle
social-email: vanessa.cassandra.s@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
